apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-dep
  labels:
    app: django_app
spec:
  replicas: 1
  selector:
    matchLabels:
      project: kuber1
  template:
    metadata:
      labels:
        project: kuber1
    spec:
      containers:
        - name: container-django
          image: django_app:latest
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: django-env
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: django-app
                  key: postgres_url
                  optional: false
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django-app
                  key: django_secret_key
                  optional: false
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: django-env
data:
  ALLOWED_HOSTS: "*"
  DEBUG: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: django-service
  labels:
    env: prod
    owner: IBA
spec:
  selector:
    project: kuber1
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: django-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: star-burger.test
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: django-service
            port:
              number: 80
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clearsessions
spec:
  startingDeadlineSeconds: 600
  schedule: "0 1 1 * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 600
      backoffLimit: 2
      activeDeadlineSeconds: 600
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: django-clearsessions
            image: django_app:latest
            imagePullPolicy: Never
            envFrom:
              - configMapRef:
                  name: django-env
            command:
              - python
              - manage.py
              - clearsessions
            env:
              - name: DATABASE_URL
                valueFrom:
                  secretKeyRef:
                    name: django-app
                    key: postgres_url
                    optional: false
              - name: SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    name: django-app
                    key: django_secret_key
                    optional: false